// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpivjikbxsjifugrypaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwaXZqaWtieHNqaWZ1Z3J5cGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA3MjksImV4cCI6MjA2NTQ5NjcyOX0.oHnfiwCttnvr6lRTfDD3kXyN40oz8TvXDSe5lMGF50M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);